회원가입, 로그인 기능완료
wecode-bootcamp-korea/36-1st-TabomGalagsin-backend pull request #3
Opened 2022-08-18 03:55 UTC by Mjj4682

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 기능과 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입
[회원가입 API] method : post,  url : /users/signup
(1). (first_name, last_name, nick_name, email, address, password) input 필요합니다.  -> 한개라도 없으면 (400, KEY_ERROR)
(2). email에 '@' 없을시 (400, EMAIL_INVALID), 비밀번호 4자리 미만시 (400, PASSWORD_INVALID), 중복 이메일 input시 (400, duplicate email)
(3). 모두 완료시 회원가입되면서 (201, userCreated)

2. 로그인
[로그인 API] method : post,  url : /users/login
(1). (email, password) input 필요합니다.  -> 한개라도 없으면 (400, KEY_ERROR)
(2). 비밀번호 틀리면 (400, Password incorrect), 이메일 틀리면 (400, This email does not exist)
(3). 모두 완료시 토큰발급되면서 (201, "accessToken" : token)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 각 에러별 상황을 처리하면서 에러핸들링에 대해서 더 자세히 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-08-19 07:49 UTC, kyeongraekim requested changes
아래 마이너한 내용 수정 해주세요! 그리고 회원가입 로그인 기능과 맞물려있을 auth.js 미들웨어도 추후에 함께 푸시해주세요~

2022-08-19 07:49 UTC, kyeongraekim commented on controllers/userController.js
> +        const beforepassword = req.body.password
- 가독성을 위해서 camelcase로 단어별 의미 구분을 지어주세요!~

2022-08-19 07:49 UTC, kyeongraekim commented on controllers/userController.js
> +        const {first_name, last_name, nick_name, email, address} = req.body
- node + javascript 기반 변수명은 snake_case가 아닌 camelCase로 진행해주세요~ 
- mysql 컨벤션으로 인해서 SQL 쿼리문에서 컬럼명을 명시할 때 제외하고 모두 camelCase를 유지해주세요!

2022-08-19 07:49 UTC, kyeongraekim commented on models/userDao.js
> +        throw err;
- 중복 가입 여부의 허용 및 예외처리 여부는 userDao가 아니라 userSevice 단에서의 checkUserDuplicacy 등의 모듈로 따로 예외처리로 진행하면 좋을 것 같네요!

2022-08-19 10:40 UTC, Mjj4682 commented on controllers/userController.js
> +        const beforepassword = req.body.password
수정했습니다~

2022-08-19 10:40 UTC, Mjj4682 commented on controllers/userController.js
> +        const {first_name, last_name, nick_name, email, address} = req.body
수정했습니다~

2022-08-19 10:40 UTC, Mjj4682 commented on models/userDao.js
> +        throw err;
수정했습니다~

2022-08-22 04:52 UTC, kyeongraekim approved these changes
LGTM!~

2022-08-22 04:52 UTC, merged