[ADD]category 별 제품조회 엔드포인트 구현
wecode-bootcamp-korea/36-1st-TabomGalagsin-backend pull request #4
Opened 2022-08-19 05:31 UTC by Seongmin-Gil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카테고리(제품종류, 색상)에 따른 해당 제품 조회 기능 엔드포인트 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 제품종류 및 색상에 따른 해당 제품 조회
- postman을 통하여 서버 정상작동 여부를 확인
- 카테고리 별 id 값을 통하여 제품타입 별 조회 및 제품 색깔별 조회 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데이터테이블 간의 복잡한 관계와 프론트에서 요청하는 데이터 형식에 맞는 값으로 데이터를 추출하기 위한
   쿼리문 작성에 어려움이 있었습니다.
- 쿼리문으로 데이터를 받는 과정에서 JSON_OBJECTAGG를 통해 color와 size의 데이터를 조회하여, 해당 JSON형식을 javascript로
- 반복문을 통한 JSON.parse해야하는 문제가 발생하였습니다.
- 색깔별로 제품을 조회할 때 해당 제품이 보유한 다른 색깔에 대한 정보를 담아오지 못하는 문제점이 발생하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- 쿼리문이 길어서 가독성에 어려움이 있는 것 같습니다. 조금 더 효율적인 방법이 없는지 고민이 필요할 것 같습니다.

2022-08-22 06:24 UTC, kyeongraekim requested changes

2022-08-22 06:24 UTC, kyeongraekim commented on controllers/categoriesController.js
> +const erroHandler = (err, res) => {
- 'error'에 대한 오타가 보입니다. 수정해주세요!~

2022-08-22 06:24 UTC, kyeongraekim commented on controllers/categoriesController.js
> +    if (Number(categoriesId) === 1) {
- 현재 "=== 1", "===2" 이라고 일치여부를 정의 내린 내용은 1번 숫자에 하드 코딩 되어있다고 볼 수 있습니다. 상용화된 코드에서는 최대한 하드코딩을 지양한 후 변수로서 정의하여 사용해주셔야 하는데, 이 때 객체지향 프로그래밍에서는 enum이라는 클래스를 만들어서 사용합니다.

- 다만 자바스크립트에서는(타입스크립트는 제공을 하는 부분임) 해당 enum이라는 클래스 Syntax를 제공하지 않음으로 이와 최대한 유사한 환경의 변수를 설정하여서 사용해볼 수 있습니다. 다음의 링크와 코드 진행방식을 한 번 참고해주세요!

```javascript
const daysEnum = Object.freeze({
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6
});
```
- 참고링크(1): https://www.30secondsofcode.org/articles/s/javascript-enum
- 참고링크(2): https://yorr.tistory.com/21

2022-08-22 06:24 UTC, kyeongraekim commented on models/categoriesDao.js
> +        throw error;
- 좀 전에 공유해주신 ERD 수정 소요가 반영되면 해당 쿼리문 부분에 수정이 필요할 것 같네요!~ ERD 변경 관련 결정을 내리신 이후에 알려주세요!

2022-08-22 06:27 UTC, kyeongraekim commented on models/categoriesDao.js
> +const searchProductsType = async (typeId) => {
자바스크립트-익스프레스 다운 변수명을 위해서 getProductsByTypeId 등으로 변경해주세요~ 변수명을 통해서 해당 모듈이 어떤 역할을 하는지 직관적으로 판단이 되어야 제 3자의 가독성과 코드 독해력이 올라갑니다.

2022-08-22 12:47 UTC, Seongmin-Gil commented on models/categoriesDao.js
> +const searchProductsType = async (typeId) => {
해당 사항 반영하여 수정완료하였습니다.

2022-08-22 12:48 UTC, Seongmin-Gil commented on models/categoriesDao.js
> +        throw error;
productions_option 테이블 추가하여 변경된 DB에 맞춰 쿼리문 수정하였습니다.

2022-08-22 12:49 UTC, Seongmin-Gil commented on controllers/categoriesController.js
> +    if (Number(categoriesId) === 1) {
이전 라운지 시간에 하셨던 이야기를 반영하여 type과 color에 따른 url을 두개로 나눠 수정하였습니다.

2022-08-22 12:49 UTC, Seongmin-Gil commented on controllers/categoriesController.js
> +const erroHandler = (err, res) => {
해당사항 수정완료하였습니다.

2022-08-23 02:06 UTC, kyeongraekim requested changes

2022-08-23 02:06 UTC, kyeongraekim commented on services/categoriesService.js
> +    const productInfos = await categoriesDao.getProductByType(categoryName);
- 이 부분은 categoryName을 인자로서 전달하고자 하는데 실제 getProductByType의 매개변수는 typeId로 설정되어있네요! 제 3자의 개발자가 독해하면서 충분히 의문을 가질 수 있는 부분 같습니다. 본래 의도하신 대로 수정해주세요!~

2022-08-23 02:06 UTC, kyeongraekim commented on controllers/categoriesController.js
> +const categoriesColor = async (req, res) => {
- 7번과 17번 라인의 변수명이 어떠한 행위적 의미를 담고있는지 변수명에 직관적으로 드러내주시면 좋을 것 같습니다.
- Dao에서 잘해주신 것처럼 Controller 단에서도 명사형이 아닌 getCategoryListByColor 정도로, 동사와 목적어 등을 명확히 나타내서 추후 디버깅이나 유닛 테스트시 다른 개발자들의 원활한 작업 또한 도와주세요!~

2022-08-23 03:36 UTC, Seongmin-Gil commented on services/categoriesService.js
> +    const productInfos = await categoriesDao.getProductByType(categoryName);
해당 사항 반영하여 코드 수정완료하였습니다.

2022-08-23 03:37 UTC, Seongmin-Gil commented on controllers/categoriesController.js
> +const categoriesColor = async (req, res) => {
해당 사항 반영하여 해당 변수명 수정완료하였습니다.

2022-08-23 04:40 UTC, kyeongraekim approved these changes
LGTM!~

2022-08-23 04:40 UTC, merged