결제페이지 API 구현
wecode-bootcamp-korea/36-1st-TabomGalagsin-backend pull request #8
Opened 2022-08-23 13:10 UTC by Mjj4682

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 결제 API 구현하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 프론트에서 headers값에 user 토근을 주면 user id값을 바탕으로 상품 상세정보를 가져옵니다.
2. user id값과 order_status_id가 2번인 데이터(결제화면)를 3번(결제 완료)로 order_status_id를 바꿉니다.
3. 포인트 차감을 위해 먼저 user point를 가져오고 프론트에서 받은 totalPrice보다 가지고 있는 point가 작으면 에러처리 하였습니다.
4. point가 더 크면 point에서 totalPrice를 빼서 데이터를 update하였습니다.
5. 결제한 상품의 색상 값을 recommend 테이블에 추가하여 구매한 색상과 같은 상품의 색상이 메인화면 홈페이지에 나오게 만들었습니다.
6. 구매한 수량을 체크하여 재고에 빼서 update하였습니다.(재고보다 많은 수량을 구매하는거는 카트에 넣는 선에서 에러핸들링 하였습니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 동적으로 insert를 하는법을 배웠고 외부 쿼리를 차단하는법에 대해서 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 동적으로 update하는거는 아무리 찾아도 못 찾아서 서비스단에서 for문을 통해 구현하였습니다.

2022-08-24 03:10 UTC, kyeongraekim requested changes

2022-08-24 03:10 UTC, kyeongraekim commented on models/orderDao.js
> +};
- 지난 번에 달아드린 Enum 관련 내용을 아래에 다시 한 번 명시해드립니다! 현재 코드 상에 숫자로 db의 어떤 컬럼의 어떤 내용을 명시하는지 드러나지 않습니다. 코드에서 명확하게 확인할 수 있게 각 상황에 맞는 orderStatusEnum, paymentStatusEnum 등을 따로 만들어서 (models 디렉토리 안 dao들과 동일 선상에서 enum들에 대한 모음집을 만들어서) 이곳에서 require 하면 좋을 것 같아 보이네요!
- 이상적인 형태는 "B.order_status_id = ${orderStatusEnum.pending}" 과 같은 형태가 될 것 입니다. 


------지난 리뷰 내역------
- 현재 "=2", "=3" 이라고 일치여부를 정의 내린 내용은 특정 숫자에 하드 코딩 되어있다고 볼 수 있습니다. 상용화된 코드에서는 최대한 하드코딩을 지양한 후 변수로서 정의하여 사용해주셔야 하는데, 이 때 객체지향 프로그래밍에서는 enum이라는 클래스를 만들어서 사용합니다.

- 다만 자바스크립트에서는(타입스크립트는 제공을 하는 부분임) 해당 enum이라는 클래스 Syntax를 제공하지 않음으로 이와 최대한 유사한 환경의 변수를 설정하여서 사용해볼 수 있습니다. 다음의 링크와 코드 진행방식을 한 번 참고해주세요!

```javascript
const daysEnum = Object.freeze({
  monday: 0,
  tuesday: 1,
  wednesday: 2,
  thursday: 3,
  friday: 4,
  saturday: 5,
  sunday: 6
});
```
- 참고링크(1): https://www.30secondsofcode.org/articles/s/javascript-enum
- 참고링크(2): https://yorr.tistory.com/21

2022-08-24 03:10 UTC, kyeongraekim commented on models/orderDao.js
> +const productDetail = async (userId) => {
이곳 Dao에서의 전체 함수 모듈들도 함수 네이밍 컨벤션에 맞추어서 명사형이 아닌 동사형으로 수정해주세요!~

2022-08-24 03:10 UTC, kyeongraekim commented on models/orderDao.js
> +const paymentQuantity = (quantityOid) => {
quantity 이후에 오타가 보이네요!~

2022-08-24 03:40 UTC, Mjj4682 commented on models/orderDao.js
> +};
수정했습니다!

2022-08-24 03:40 UTC, Mjj4682 commented on models/orderDao.js
> +const productDetail = async (userId) => {
수정했습니다!

2022-08-24 03:40 UTC, Mjj4682 commented on models/orderDao.js
> +const paymentQuantity = (quantityOid) => {
수정했습니다!

2022-08-24 05:16 UTC, kyeongraekim requested changes

2022-08-24 05:16 UTC, kyeongraekim commented on models/orderDao.js
> +const { orderStatus } = require('../util/enum');
- layered pattern을 적용한 이후에는 새로운 디렉토리 형성 시 많은 고민을 해주시고 내가 의도하는 모듈의 위치를 선정해주셔야 합니다. Dao 단 내에서만 활용될 enum이기 때문에 enum의 위치를 루트 디렉토리가 아닌 models 폴더 내부로 옮기는 것을 권장드립니다.
- 그리고 enum의 naming 컨벤션은 보통 뒤에 Enum을 지정하는 편이기 때문에 네이밍을 한 번 더 수정해주면 좋을 것 같습니다.

2022-08-24 05:16 UTC, kyeongraekim commented on models/orderDao.js
> +const paymentStatusAdd = (userId) => {
- 이곳은 order 주문에 대한 데이터 이력 관리가 이루어지는 모듈로 보여지네요. payment의 상태 관리와는 다소 차이가 있어 보입니다.

2022-08-24 05:54 UTC, Mjj4682 commented on models/orderDao.js
> +const { orderStatus } = require('../util/enum');
수정했습니다!

2022-08-24 05:54 UTC, Mjj4682 commented on models/orderDao.js
> +const paymentStatusAdd = (userId) => {
수정했습니다!

2022-08-25 02:58 UTC, kyeongraekim requested changes

2022-08-25 02:58 UTC, kyeongraekim commented on controllers/orderController.js
> +        res.status(err.statusCode || 500).json({message : err.message})
이제 에러핸들링에 대한 미들웨어 적용 및 리팩토링을 마지막으로 진행해보시죠!

Error 객체를 만들 때에도 굉장히 많은 코드가 중복되는 것을 느끼셨을 것 같습니다.

Node.js 내장 Error 객체를 사용하는 것은 대부분의 개발자가 오류의 근원을 추적하기 위해 의존하는 StackTrace와 같은 오류에 대한 직관적이고 명확한 정보를 포함하고 있기 때문에 좋은 방법입니다. 그리고 HTTP 상태 코드와 같은 의미 있는 추가 속성과 Error 클래스를 확장하여 설명을 추가하면 더 많은 정보를 얻을 수 있습니다.

예를 들어서 아래와 같이 사용할 수 있겠습니다.



```javascript
class BaseError extends Error {
	constructor(name, httpStatusCode, description) {
		super(description);

		this.name = name;
		this.httpCode = httpStatusCode;

		Error.captureStackTrace(this);
	}
}

if (user === null)
	throw new BaseError(
		'NOT FOUND',
		HttpStatusCode.NOT_FOUND,
		true,
		'detailed explanation'
);

```

2022-08-25 03:05 UTC, kyeongraekim requested changes

2022-08-25 03:05 UTC, kyeongraekim commented on services/orderService.js
> +    for(let pDetail of productDetail){
pDetail 관련 변수명 한 번만 더 신경써주세요!~

2022-08-25 04:06 UTC, Mjj4682 commented on controllers/orderController.js
> +        res.status(err.statusCode || 500).json({message : err.message})
아직 필터링 api를 못 올려서 모든 기능 api 머지되면 리팩토링해도될까요??

2022-08-25 04:07 UTC, Mjj4682 commented on services/orderService.js
> +    for(let pDetail of productDetail){
수정했습니다!

2022-08-25 05:10 UTC, kyeongraekim approved these changes
LGTM!~ 에러 핸들링 리팩토링은 추후 푸시에서 함께 진행해주세요!~

2022-08-25 05:10 UTC, merged